import { DocstringTooltip } from "./docstring-tooltip";
import { Item, ItemTitle } from "@/components/ui/item";
import { Badge } from "@/components/ui/badge";
import type { FrontendNodeData } from "@/types/types";

interface DraggableNodeProps {
  nodeData: FrontendNodeData;
}

export function DraggableNode({ nodeData }: DraggableNodeProps) {
  const onDragStart = (event: React.DragEvent<HTMLDivElement>) => {
    event.dataTransfer.setData(
      "application/reactflow",
      JSON.stringify(nodeData),
    );
    event.dataTransfer.effectAllowed = "move";
  };

  return (
    <DocstringTooltip description={nodeData.doc || ""}>
      <Item
        variant="outline"
        className="p-2 cursor-grab hover:bg-accent hover:text-accent-foreground"
        onDragStart={onDragStart}
        draggable
      >
        <div className="flex items-center justify-between gap-2 w-full">
          <ItemTitle className="pb-0">{nodeData.name}</ItemTitle>
          {nodeData.autoGenerated && (
            <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
              {nodeData.callableId.startsWith("subflow:") ? "sub-flow" : "auto"}
            </Badge>
          )}
        </div>
      </Item>
    </DocstringTooltip>
  );
}
