import { DocstringTooltip } from "./docstring-tooltip";
import { Item, ItemTitle } from "@/components/ui/item";
import { Badge } from "@/components/ui/badge";
import type { FrontendNodeData } from "@/types/types";

interface DraggableNodeProps {
  nodeData: FrontendNodeData;
}

export function DraggableNode({ nodeData }: DraggableNodeProps) {
  const onDragStart = (event: React.DragEvent<HTMLDivElement>) => {
    event.dataTransfer.setData(
      "application/reactflow",
      JSON.stringify(nodeData),
    );
    event.dataTransfer.effectAllowed = "move";
  };

  return (
    <DocstringTooltip description={nodeData.doc || ""}>
      <Item
        variant="outline"
        className="h-7 min-h-7 cursor-grab px-2 py-0 hover:bg-accent hover:text-accent-foreground"
        onDragStart={onDragStart}
        draggable
      >
        <div className="flex h-full w-full min-w-0 items-center gap-2">
          <div className="min-w-0 flex-1">
            <ItemTitle className="block w-full truncate pb-0">
              {nodeData.name}
            </ItemTitle>
          </div>
          {nodeData.autoGenerated && (
            <Badge variant="secondary" className="shrink-0 text-[10px] px-1.5 py-0">
              {nodeData.callableId.startsWith("subflow:") ? "sub-flow" : "auto"}
            </Badge>
          )}
        </div>
      </Item>
    </DocstringTooltip>
  );
}
