import { useState, useMemo } from "react";
import { SearchBar } from "@/common/utility-components/search-bar";
import { CategoryGroup } from "./category-group";
import { Checkbox } from "@/components/ui/checkbox";
import useNodeSchemas, { type NodesResponse } from "@/hooks/useNodeSchemas";
import type { FrontendNodeData } from "@/types/types";

type FunctionSchemaWithGroup = FrontendNodeData & { group: string };

interface NodeCategories {
  [category: string]: FunctionSchemaWithGroup[];
}

function NodePicker() {
  const { nodeSchemas, refetch } = useNodeSchemas();
  const [searchTerm, setSearchTerm] = useState("");
  const [showAutoGenerated, setShowAutoGenerated] = useState(true);

  const transformNodeFunctionDataToNodes = (
    data: NodesResponse,
  ): NodeCategories => {
    const categories: NodeCategories = {};

    Object.entries(data).forEach(([, functionSchema]) => {
      // Use the first element of category array as the main category
      const mainCategory = functionSchema.category[0] || "Uncategorized";
      // Use the second element as the group (file name)
      const group = functionSchema.category[1] || "Default";

      const nodeData: FunctionSchemaWithGroup = {
        ...functionSchema,
        group: group,
      };
      // Initialize category if it doesn't exist
      if (!categories[mainCategory]) {
        categories[mainCategory] = [];
      }

      categories[mainCategory].push(nodeData);
    });

    return categories;
  };

  const nodeCategories = useMemo(() => {
    return transformNodeFunctionDataToNodes(nodeSchemas);
  }, [nodeSchemas]);

  

  const filteredCategories = Object.entries(nodeCategories).reduce(
    (acc, [category, nodes]) => {
      // Filter out auto-generated nodes if checkbox is unchecked
      const nodesToProcess = showAutoGenerated
        ? nodes
        : nodes.filter((node) => !node.autoGenerated);

      // Group nodes by their group attribute
      const groupedNodes = nodesToProcess.reduce<
        Record<string, FunctionSchemaWithGroup[]>
      >((groups, node) => {
        const group = node.group || "Ungrouped";
        if (!groups[group]) {
          groups[group] = [];
        }
        groups[group].push(node);
        return groups;
      }, {});

      // Filter nodes based on search term
      const filteredGroups: Record<string, FunctionSchemaWithGroup[]> = {};
      Object.entries(groupedNodes).forEach(([group, groupNodes]) => {
        const filteredNodes = groupNodes.filter((node) =>
          node.name.toLowerCase().includes(searchTerm.toLowerCase()),
        );
        if (filteredNodes.length > 0) {
          filteredGroups[group] = filteredNodes;
        }
      });

      if (
        Object.keys(filteredGroups).length > 0 ||
        category.toLowerCase().includes(searchTerm.toLowerCase())
      ) {
        acc[category] = nodesToProcess.filter((node) =>
          node.name.toLowerCase().includes(searchTerm.toLowerCase()),
        );
        acc[category].groups = filteredGroups;
      }
      return acc;
    },
    {} as NodeCategories & {
      [key: string]: { groups?: Record<string, FunctionSchemaWithGroup[]> };
    },
  );

  return (
    <div className="h-full flex flex-col px-2 pt-2 gap-2">
      <SearchBar
        searchTerm={searchTerm}
        onSearchChange={setSearchTerm}
        onRefresh={refetch}
        placeholder="Search nodes..."
        refreshTitle="Refresh functions"
        ariaLabel="Search nodes"
      />
      <div className="flex items-center space-x-2 px-1">
        <Checkbox
          id="show-auto-generated"
          checked={showAutoGenerated}
          onCheckedChange={(checked) =>
            setShowAutoGenerated(checked as boolean)
          }
        />
        <label
          htmlFor="show-auto-generated"
          className="text-xs text-muted-foreground cursor-pointer select-none"
        >
          Show auto-generated nodes
        </label>
      </div>
      <div className="flex flex-col justify-start items-start pb-1 overflow-y-auto flex-1 min-h-0 scrollbar-hide">
        {Object.entries(filteredCategories).map(
          ([category, categoryData], index) => (
            <CategoryGroup
              key={category}
              category={category}
              categoryData={categoryData}
              showDivider={index > 0}
            />
          ),
        )}
      </div>
    </div>
  );
}

export default NodePicker;
