export interface UnionDescrJson {
  anyOf: string[];
}

export interface StructDescrJson {
  structureType: "list" | "dict";
  itemsType: string | UnionDescrJson;
}

export type TypeExprJson = string | UnionDescrJson | StructDescrJson;

export interface DataWrapperJson {
  type: TypeExprJson;
  value: unknown | null;
}

export interface FunctionSchemaJson {
  name: string;
  callableId: string;
  category: string[];
  definitionPath: string;
  doc?: string | null;
  arguments: Record<string, DataWrapperJson>;
  dynamicInputType?: StructDescrJson | null;
  outputStyle?: "single" | "multiple";
  outputs: Record<string, DataWrapperJson>;
  cachedTypes?: string[];
  autoGenerated?: boolean;
}

export interface BuiltinTypeDefJson {
  kind: "builtin";
}

export interface UserTypeDefJson {
  kind: "user_model";
  category: string[];
  properties?: Record<string, TypeExprJson> | null;
}

export interface CachedTypeDefJson {
  kind: "cached";
  category: string[];
}

export interface UnknownTypeDefJson {
  kind: string;
  [key: string]: unknown;
}

export type TypeDefJson =
  | BuiltinTypeDefJson
  | UserTypeDefJson
  | CachedTypeDefJson
  | UnknownTypeDefJson;
