export interface UnionDescr {
  anyOf: string[];
}

export interface StructDescr {
  structureType: "list" | "dict";
  itemsType: string | UnionDescr;
}

export type TypeSchema = string | UnionDescr | StructDescr;

export interface DataWrapper {
  type: TypeSchema;
  value?: unknown | null;
}

export interface FunctionSchema {
  name: string;
  callableId: string;
  category: string[];
  definitionPath: string;
  doc?: string | null;
  arguments: Record<string, DataWrapper>;
  dynamicInputType?: StructDescr | null;
  outputStyle?: "single" | "multiple";
  outputs: Record<string, DataWrapper>;
  cachedTypes?: string[];
  autoGenerated?: boolean;
}
