export interface UnionDescr {
  anyOf: string[];
}

export interface StructDescr {
  structureType: "list" | "dict";
  itemsType: string | UnionDescr;
}

export type TypeExpr = string | UnionDescr | StructDescr;

export interface DataWrapper {
  type: TypeExpr;
  value?: unknown | null;
}

export interface FunctionSchema {
  name: string;
  callableId: string;
  category: string[];
  definitionPath: string;
  doc?: string | null;
  arguments: Record<string, DataWrapper>;
  dynamicInputType?: StructDescr | null;
  outputStyle?: "single" | "multiple";
  outputs: Record<string, DataWrapper>;
  cachedTypes?: string[];
  autoGenerated?: boolean;
}

export interface BuiltinTypeDef {
  kind: "builtin";
}

export interface UserTypeDef {
  kind: "user_model";
  category: string[];
  properties?: Record<string, TypeExpr> | null;
}

export interface CachedTypeDef {
  kind: "cached";
  category: string[];
}

export interface UnknownTypeDef {
  kind: string;
  [key: string]: unknown;
}

export type TypeDef =
  | BuiltinTypeDef
  | UserTypeDef
  | CachedTypeDef
  | UnknownTypeDef;
