import type { Node } from "@xyflow/react";

export interface CachedValueReference {
  instanceType?: string;
  cacheKey: string;
  preview?: string;
  displayName?: string;
  filename?: string;
  [key: string]: unknown;
}

export type BaseDataTypes =
  | number
  | string
  | boolean
  | CachedValueReference
  | Record<string, unknown>
  | unknown[];

export interface StructDescr {
  structureType: "list" | "dict";
  itemsType: string | UnionDescr;
}

export interface UnionDescr {
  anyOf: string[];
}

export interface DataWrapper {
  type: string | StructDescr | UnionDescr;
  value: BaseDataTypes | null;
}

// This is a frontend-only type that extends DataWrapper with UI state
export interface FrontendFieldDataWrapper extends DataWrapper {
  _selectedType?: string;
  _showPreview?: boolean;
  _structuredInputType?: "list" | "dict";
  _expanded?: boolean;
}

export interface FunctionSchema {
  name: string;
  callableId: string;
  category: string[];
  definitionPath: string;
  doc?: string | null;
  arguments: Record<string, FrontendFieldDataWrapper>;
  dynamicInputType?: StructDescr | null;
  outputStyle?: "single" | "multiple";
  outputs: Record<string, FrontendFieldDataWrapper>;
  cachedTypes?: string[];
  autoGenerated?: boolean;
  [key: string]: unknown;
}

export interface FrontendNodeData extends FunctionSchema {
  terminalOutput?: string;
  _terminal_drawer?: {
    _expanded?: boolean;
    _expandedHeight?: number;
  };
  status?: "not-executed" | "executed" | "error" | "executing";
}

export type FunctionNode = Node<FrontendNodeData, "customNode">;

export interface NodeUpdate {
  nodeId: string;
  status?: "executing" | "executed" | "error";
  outputs?: Record<string, FrontendFieldDataWrapper>;
  arguments?: Record<string, FrontendFieldDataWrapper>;
  terminalOutput?: string;
}
